# Generated by Django 3.2.3 on 2021-05-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='first',
            new_name='tally',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='second',
        ),
    ]
