# Generated by Django 3.2.3 on 2021-05-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210525_0724'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calculator',
            table='calculator_calculator',
        ),
    ]
