# Generated by Django 3.2.3 on 2021-05-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_calculator_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calculator',
            table='calculator',
        ),
    ]
