# Generated by Django 3.2.3 on 2021-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_calculator_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='calculation_id',
        ),
        migrations.AlterField(
            model_name='calculator',
            name='tally',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
